/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Madvotes.types";
import * as _1 from "./Madvotes.client";
import * as _2 from "./Madvotes.message-composer";
import * as _3 from "./Madvotes.react-query";
import * as _4 from "./Madvotes.message-builder";
import * as _5 from "./Madvotes.provider";
import * as _6 from "./contractContextProviders";
import * as _7 from "./contractContextBase";
import * as _8 from "./contracts-context";
export namespace contracts {
  export const Madvotes = {
    ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4,
    ..._5
  };
  export const undefined = {
    ..._6
  };
  export const contractContextBase = {
    ..._7
  };
  export const contractsContext = {
    ..._8
  };
}