/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { IQueryClientProvider, ISigningClientProvider, IMessageComposerProvider } from "./contractContextBase";
import { MadvotesQueryClient } from "./Madvotes.client";
import { MadvotesClient } from "./Madvotes.client";
import { MadvotesMsgComposer } from "./Madvotes.message-composer";
import { Madvotes } from "./Madvotes.provider";
export interface IContractsContext {
  madvotes: IQueryClientProvider<MadvotesQueryClient> & ISigningClientProvider<MadvotesClient> & IMessageComposerProvider<MadvotesMsgComposer>;
}
export const getProviders = (address?: string, cosmWasmClient?: CosmWasmClient, signingCosmWasmClient?: SigningCosmWasmClient) => ({
  madvotes: new Madvotes({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  })
});