/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admin: string;
  burn_bps: number;
  min_bet: Uint128;
}
export type ExecuteMsg = {
  register_market: {
    proposal: Proposal;
    proposal_id: number;
  };
} | {
  place_bet: {
    outcome: Outcome;
    proposal_id: number;
  };
} | {
  settle_market: {
    proposal: Proposal;
    proposal_id: number;
  };
} | {
  claim: {
    proposal_id: number;
  };
};
export type ProposalStatus = "unspecified" | "deposit_period" | "voting_period" | "passed" | "rejected" | "failed";
export type Outcome = "passed" | "rejected" | "veto_rejected" | "quorum_failed";
export interface Proposal {
  deposit_end_time?: number | null;
  expedited: boolean;
  failed_reason: string;
  id: number;
  metadata: string;
  proposer: string;
  status: ProposalStatus;
  submit_time?: number | null;
  summary: string;
  tally?: Tally | null;
  title: string;
  voting_end_time?: number | null;
  voting_start_time?: number | null;
}
export interface Tally {
  abstain_count: string;
  no_count: string;
  no_with_veto_count: string;
  yes_count: string;
}
export type QueryMsg = {
  get_proposal: {
    proposal_id: number;
  };
} | {
  get_market: {
    proposal_id: number;
  };
} | {
  get_position: {
    depositor: string;
    proposal_id: number;
  };
} | {
  get_pools: {
    proposal_id: number;
  };
} | {
  get_claim: {
    depositor: string;
    proposal_id: number;
  };
} | {
  list_markets: {
    limit?: number | null;
    start_after?: number | null;
    status?: MarketStatus | null;
  };
};
export type MarketStatus = "open" | "settled";
export interface ClaimResponse {
  already_claimed: boolean;
  depositor: string;
  /**
   * The depositor's payout for this market. While `already_claimed` is false
   * this is the amount still claimable (exact once settled; "0" before
   * settlement or for non-winners); once `already_claimed` is true it is the
   * amount that was actually paid out.
   */
  payout: Uint128;
  proposal_id: number;
  settled: boolean;
}
export interface MarketResponse {
  proposal_id: number;
  status: MarketStatus;
  title: string;
  voting_end_time: number;
  voting_start_time: number;
  winning_outcome?: Outcome | null;
}
export type Uint256 = string;
export interface PoolsResponse {
  pools: OutcomeAccum[];
  proposal_id: number;
}
export interface OutcomeAccum {
  net: Uint128;
  outcome: Outcome;
  weighted: Uint256;
}
export interface PositionResponse {
  depositor: string;
  positions: OutcomeAccum[];
  proposal_id: number;
}
export interface MarketsResponse {
  markets: MarketResponse[];
}