/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { MadvotesClient, MadvotesQueryClient } from "./Madvotes.client";
import { MadvotesMsgComposer } from "./Madvotes.message-composer";
export class Madvotes extends ContractBase<MadvotesClient, MadvotesQueryClient, MadvotesMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, MadvotesClient, MadvotesQueryClient, MadvotesMsgComposer);
  }
}