/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, InstantiateMsg, ExecuteMsg, ProposalStatus, Outcome, Proposal, Tally, QueryMsg, MarketStatus, ClaimResponse, MarketResponse, Uint256, PoolsResponse, OutcomeAccum, PositionResponse, MarketsResponse } from "./Madvotes.types";
import { CamelCasedProperties } from "type-fest";
export abstract class MadvotesExecuteMsgBuilder {
  static registerMarket = ({
    proposal,
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_market: unknown;
  }>["register_market"]>): ExecuteMsg => {
    return {
      register_market: ({
        proposal,
        proposal_id: proposalId
      } as const)
    };
  };
  static placeBet = ({
    outcome,
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    place_bet: unknown;
  }>["place_bet"]>): ExecuteMsg => {
    return {
      place_bet: ({
        outcome,
        proposal_id: proposalId
      } as const)
    };
  };
  static settleMarket = ({
    proposal,
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    settle_market: unknown;
  }>["settle_market"]>): ExecuteMsg => {
    return {
      settle_market: ({
        proposal,
        proposal_id: proposalId
      } as const)
    };
  };
  static claim = ({
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim: unknown;
  }>["claim"]>): ExecuteMsg => {
    return {
      claim: ({
        proposal_id: proposalId
      } as const)
    };
  };
}
export abstract class MadvotesQueryMsgBuilder {
  static getProposal = ({
    proposalId
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_proposal: unknown;
  }>["get_proposal"]>): QueryMsg => {
    return {
      get_proposal: ({
        proposal_id: proposalId
      } as const)
    };
  };
  static getMarket = ({
    proposalId
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_market: unknown;
  }>["get_market"]>): QueryMsg => {
    return {
      get_market: ({
        proposal_id: proposalId
      } as const)
    };
  };
  static getPosition = ({
    depositor,
    proposalId
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_position: unknown;
  }>["get_position"]>): QueryMsg => {
    return {
      get_position: ({
        depositor,
        proposal_id: proposalId
      } as const)
    };
  };
  static getPools = ({
    proposalId
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_pools: unknown;
  }>["get_pools"]>): QueryMsg => {
    return {
      get_pools: ({
        proposal_id: proposalId
      } as const)
    };
  };
  static getClaim = ({
    depositor,
    proposalId
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_claim: unknown;
  }>["get_claim"]>): QueryMsg => {
    return {
      get_claim: ({
        depositor,
        proposal_id: proposalId
      } as const)
    };
  };
  static listMarkets = ({
    limit,
    startAfter,
    status
  }: CamelCasedProperties<Extract<QueryMsg, {
    list_markets: unknown;
  }>["list_markets"]>): QueryMsg => {
    return {
      list_markets: ({
        limit,
        start_after: startAfter,
        status
      } as const)
    };
  };
}